type Task {
  _: Boolean
}

interface IStep {
  number: Int
  optional: Boolean
  premium: Boolean
}

type HyperlinkStep implements IStep {
  hyperlink: URL
}

type ScreenShot {
  imageUrl: URL
}

"""
better be a scala type?
"""
type URL {
  string: String
}

type Step {
  _: Boolean
  optional: Boolean
  premium: Boolean
  number: Int
}

type Code {
  _: Boolean
}

type Command {
  _: Boolean
}

type UIoperation {
  _: Boolean
}

type Result {
  _: Boolean
}

type EmbeddedVideo {
  _: Boolean
}

type EmbeddedImage {
  _: Boolean
}
