type Task {
  _: Boolean
}

type Step {
  _: Boolean
  optional: Boolean
  premium: Boolean
  number: Int
}

type Code {
  _: Boolean
}

type Command {
  _: Boolean
}

type UIoperation {
  _: Boolean
}

type Result {
  _: Boolean
}

type EmbeddedVideo {
  _: Boolean
}

type EmbeddedImage {
  _: Boolean
}
