type Query {
  recommendedUsers: [User]
  tweets: [Tweet]
  timeline: Timeline
}

scalar TimeStamp

type Timeline {
  tweets: [Tweet]
}

type User {
  id: String
  screenName: String
  url: String
  profileImageUrl: String
}

type Category {
  name: String
}

type Topic {
  name: String
  category: Category
}

type Tweet {
  id: ID
  user: User
  createdAt: TimeStamp
  fullText: String
  favoriteCount: Int
  replyCount: Int
  retweetCount: Int
  quoteCount: Int
}
